name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  upload_tarball:
    name: Upload Tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: ci/environment_linux.yml
          python-version: "3.10"
          auto-activate-base: false

      - name: Upload tarball
        shell: bash -l {0}
        run: |
            export SSH_DEPLOY_KEY=${{ secrets.SSH_DEPLOY_KEY }}
            ./build0.sh
            lfortran_version=$(<version)
            sudo apk add --no-cache cmake
            ci/create_source_tarball.sh $lfortran_version
            ci/upload_tarball.sh
