name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master


jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: ci/environment_linux.yml

      - name: Install/Update Packages
        shell: bash -l {0}
        run: |
            sudo apt-get update
            sudo apt-get install -yq --no-install-recommends openssh-client git
            conda install -c conda-forge nbconvert=5.6.0 mkdocs=1.3.0
            pip install mkdocs-material==8.2.16 jupyter_client==6.1.12

      - name: Build Docs
        shell: bash -l {0}
        run: |
            xonsh ci/make_docs.xsh

      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: Documentation Site
          path: |
            doc/site
